export { default as Footer } from './Footer'
export { default as NavBar } from './NavBar'
export { default as Home } from './Home'
export { default as Movie } from './Movie'
export { default as SearchBar } from './pieces/SearchBar'
export { default as Banner } from './pieces/Banner'